# docker-composeのバージョン
version: "3.4"
# services配下に各コンテナの情報を記載する
services:
  swagger-ui:
    image: redocly/redoc
    container_name: "swagger-ui"
    ports:
      - "8002:80"
    volumes:
      - ./swagger/tyoto_todo.yaml:/usr/share/nginx/html/swagger.yaml
    environment:
      SPEC_URL: swagger.yaml