openapi: "3.0.0"
info:
  title: ちょっとすごいTODOのAPI
  description: わはははは
  termsOfService: 'https://github.com/konowohagemasuheya/tyoto_todo'
  version: 1.0.1
paths:
  /api/todos:
    get:
      responses:
        200:
          description: ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ToDo"
components:
  schemas:
    ToDo:
      type: object
      required:
        - id
        - create_at
      properties:
        id:
          type: number
          example: 1
        title:
          description: タイトル
          required:
            - title
          type: string
          example: タスク1
        detail:
          description: 詳細テキスト
          required:
            - detail
          type: string
          example: 'これこれをやる'
        create_at:
          description: 作成日時
          type: string
          format: date-time
        update_at:
          description: 更新日時
          nullable: true
          type: string
          format: date-time