name: Create PullRequest or Commit Of Front Directory

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - feature/recoil
      - master
env:
  cache-version: v1
jobs:
  test:
    name: run static tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          # 該当するプルリクの最新のcommitを取得
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Node setup
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - uses: actions/cache@v2
        with:
          path: |
            ${{ steps.npm-cache.outputs.dir }}
            **/node_modules
          key: ${{ runner.os }}-${{ env.cache-version }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: echo node version
        run: node -v
      - name: npm install
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install
      - name: Test
        run: npm test --no-cache
